name: CI

on:
  # By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened.
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
  # So we add default event types and ready_for_review type here.
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - run: make test

  lint:
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          only-new-issues: true

